"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _blog_card from './blog-card.bones.json'

configureBoneyard({"color":"#e5e5e5","animate":"pulse"})

registerBones({
  "blog-card": _blog_card,
})
